patrol_node:
  ros__parameters:
    initial_point: [0.0, 0.0, 0.0]
    target_points: [
      0.0,0.0,0.0,
      1.0,2.0,3.14,
      0.0,0.0,0.0,
      1.0,2.0,3.14,
      0.0,0.0,0.0,
      ]
    use_sim_time: true